### ISSUE TITLE
[yurtctl] Conversion job template modification

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#423]
**Background**:
yurtctl convert/revert issues Job tasks to convert nodes. Jobs enter the host's file system through `nsenter` to modify the files on the host, which can refer to the file `pkg/yurtctl/constants/constants.go`.

**What would you like to be added**:
1.In order to limit the scope of files modified by yurtctl, modify the way yurtctl manipulates host files, that is, not to use `nsenter`.
2.Improved the ways of `EnableNodeControllerJobTemplate` and `DisableNodeControllerJobTemplate` (in file `pkg/yurtctl/constants/constants.go`) to modify file content (recommended to use golang code to manipulate files), so that all situations can be handled correctly.

**Why is this needed**:
1.`nsenter` makes Job share the file system of the host, and Job can obtain/modify any file on the host, which has security issues.
2.`sed` cannot cover all the cases of the parameter --controllers in the kube-controller-manager static deployment file, such as the case where the parameter does not exist. In addition, yaml files have strict requirements on the format, and `sed` cannot achieve elegant modification.

**others**
/kind enhancement
/kind bug

**Comment by rambohe-ch** [comment]
@adamzhoul This issue maybe solved by `yurt-node-servant`, and we can close this issue after `yurtctl convert/revert` refactor.

**Comment by adamzhoul** [comment]
I see here issues two problems

1. `nsenter` introduce a security problem: we can modify any files on the host

Unfortunately, yurt-node-servant uses volume + chroot to avoid using nsenter.
But, the problem remains I think.
The core problem is we don't know which file job will use. 

2.  Improved the ways of EnableNodeControllerJobTemplate and DisableNodeControllerJobTemplate

For now, it uses sed to simply update the config.
It's still not changed yet.
And, I think we should clearly specify some cases that sed won't satisfy.

**Comment by rambohe-ch** [comment]
> I see here issues two problems
> 
> 1. `nsenter` introduce a security problem: we can modify any files on the host
> 
> Unfortunately, yurt-node-servant uses volume + chroot to avoid using nsenter. But, the problem remains I think. The core problem is we don't know which file job will use.

@adamzhoul @Peeknut In my opinion, replace `nsenter` is not security consideration, `nsenter` is not common way to manipulate host files, so we need to refactor and use `volume + chroot` to avoid using nsenter. so case 1 maybe solved by `yurt-node-servant`.

> 1. Improved the ways of EnableNodeControllerJobTemplate and DisableNodeControllerJobTemplate
> 
> For now, it uses sed to simply update the config. It's still not changed yet. And, I think we should clearly specify some cases that sed won't satisfy.

Yes, case 2 is waiting to be solved.
